config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('cocktails')

  resources :cocktails do
    resources :doses
  end
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  # validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"], allow_nil: false }
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attachments :photos, maximum: 2
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :restrict_with_exception
  has_many :cocktails, through: :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [:show, :edit, :update, :destroy]
  def index
    @cocktails = Cocktail.all
  end

  def show
    @doses = @cocktail.doses
    # @ingredients = @cocktail.ingredients
  end

  def new
    @cocktail = Cocktail.new
    # @dose = Dose.new
    # @dose.cocktail_id = @cocktail.id
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new" # si le cocktail n'est pas cree avec des attributs valides, on est redirigé vers le formulaire de new
    end

  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private
  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
  def cocktail_params
    params.require(:cocktail).permit(:name, photos: [])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, only: [ :new, :create, :edit, :update, :destroy ]
  before_action :find_dose, only: [:edit, :update, :destroy]

  # a completer

  def new
    @dose = Dose.new
    # @ingredients = Ingredient.pluck(:name)
    @ingredients = Ingredient.all # sert à pouvoir afficher tous les ingredients dans une liste deroulante sur le formulaire.
  end

  def create
    # ingredient = Ingredient.find(dose_params[:ingredient_id])
    @dose = Dose.new(dose_params)
    # @dose.ingredient = ingredient
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "new" # si la dose n'est pas creee avec des attributs valides, on est redirigé vers le formulaire de new
    end

  end

  def edit
    @ingredients = Ingredient.all
  end

  def update
    # ingredient = Ingredient.find(dose_params[:ingredient_id])
    @dose.update(dose_params)
    # @dose.ingredient = ingredient
    @dose.cocktail = @cocktail
    @dose.save
    # if @dose.save
    #   redirect_to cocktail_path(@cocktail)
    # else
    #   render "new"
    # end
    # @review.update(review_params)
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end
  def find_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/edit.html.erb
<h1>Edit data about <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.input :photos, as: :attachinary %>
  <%= f.submit "Update cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<h1>All the good cocktails you need to know about : </h1>

<% @cocktails.each do |cocktail| %>
  <h3><%= link_to cocktail.name, cocktail_path(cocktail) %></h3>
  <%= link_to cocktail_path(cocktail) do %>
    <i class="fa fa-eye" aria-hidden="true"></i>
  <% end %>
  <%= link_to edit_cocktail_path(cocktail) do %>
    <i class="fa fa-pencil" aria-hidden="true"></i>
  <% end %>
  <%= link_to cocktail_path(cocktail), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash" aria-hidden="true"></i>
  <% end %>

  <!-- <p><strong><%= cocktail %></strong></p>
  <span>- <%= cocktail %> - <%= cocktail %></span> -->
  <p>----</p>
<%end%>

<br>
<br>
<p><%= link_to 'Create a new cocktail', new_cocktail_path, class: "btn btn-primary" %></p>

app/views/cocktails/new.html.erb
<h1>Create a new cocktail</h1>

<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.input :photos, as: :attachinary %>
  <%= f.submit "Add a cocktail", class: "btn btn-primary" %>
<% end %>

<br>
<br>
<%= link_to 'Home', cocktails_path, class: "btn btn-primary" %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<% @cocktail.photos.each do |photo| %>
  <%= cl_image_tag photo.path, width: 300, height: 200, crop: :fill %>
<% end %>

<p><%= link_to 'Edit cocktail', edit_cocktail_path(@cocktail)%></p>

<h3>Ingredients</h3>
<% @doses.each do |dose| %>
  <p> - <%= dose.description %> <%= dose.ingredient.name.capitalize %> </p>
  <%= link_to edit_cocktail_dose_path(@cocktail, dose) do %>
    <i class="fa fa-pencil" aria-hidden="true"></i>
  <% end %>
  <%= link_to cocktail_dose_path(@cocktail, dose), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash" aria-hidden="true"></i>
  <% end %>
<%end%>

<p>---------------</p>

<%= link_to 'Add a dose', new_cocktail_dose_path(@cocktail), class: "btn btn-primary" %>

<%= link_to 'Home', cocktails_path, class: "btn btn-primary" %>

app/views/doses/edit.html.erb
<h1>Edit the dose for <%= @cocktail.name.capitalize %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.submit "Edit dose", class: "btn btn-primary" %>
<% end %>

<br>
<br>
<%= link_to 'Home', cocktails_path, class: "btn btn-primary" %>

app/views/doses/new.html.erb
<h1>Create a new dose for <%= @cocktail.name.capitalize %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.input :ingredient_id, collection: @ingredients %>
  <%= f.submit "Add a dose", class: "btn btn-primary" %>
<% end %>

<br>
<br>
<%= link_to 'Home', cocktails_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>